### ISSUE TITLE
Add an option to spit out the value required to clear the notification LED. 

### ISSUE THREAD

**Issue by ChrisLizon** [nathanfiscus/inovelli-notification-calc#1]
Hello Nathan, 
This isn't actually an issue, but more of a feature request. Would it be possible to add a reminder that sending the value "0" will clear the notification indicator? One option may be to move the effect drop down to the top, and disable the color picker when something along the lines "clear notification" or "no notification" is chosen.

**Comment by nathanfiscus** [comment]
Thanks for the feedback!  I will look into it.

**Comment by nathanfiscus** [comment]
This was released as part of version 2.1. Thanks again for the feedback.
