### ISSUE TITLE
LED color 255 is white

### ISSUE THREAD

**Issue by emiliosic** [nathanfiscus/inovelli-notification-calc#7]
First, thanks a lot for this very helpful and well designed tool.
The LED color 255 is actually white(ish), meaning R, G and B LEDs are on at roughly the same intensity, so it looks about white. Tested this with Inovelli FW 1.47 on LZW31-SN dimmer.
Also, it would be good to remind users that the setting 13 on the Gen2 Dimmer is a 2-byte value, although the range is only 0-255

**Comment by nathanfiscus** [comment]
I'm working on adding a feature to allow you to change the selected firmware per switch in to address the latest firmware changes and the issue you have referenced above.  This will still allow the users that have not installed the latest firmware to see an accurate representation of their switch and provide support for future changes to the firmware or future alternative firmwares.

**Comment by nathanfiscus** [comment]
Resolved in PR #10
