### ISSUE TITLE
Fan+Light missing up/down scenes

### ISSUE THREAD

**Issue by mmiller7** [nathanfiscus/inovelli-notification-calc#9]
The "scenes" tab for the fan+light switch is missing the values for setting up scenes on single-press up/down (both fan and light).

Reference document:
https://support.inovelli.com/portal/en/kb/articles/how-to-setting-up-scenes-in-home-assistant

**Comment by nathanfiscus** [comment]
Thanks for opening an issue.  This is being resolved in an upcoming release.

**Comment by nathanfiscus** [comment]
Resolved in PR #10
